"""fix-job-status-and-add-remarks-to-job

Revision ID: 6d2e958d03b4
Revises: 73f9f410b064
Create Date: 2026-01-16 08:44:50.203505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2e958d03b4'
down_revision: Union[str, Sequence[str], None] = '73f9f410b064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'remarks')
    # ### end Alembic commands ###
