"""fix-job-status-and-job-runs

Revision ID: 73f9f410b064
Revises: 1a1a588e7161
Create Date: 2026-01-15 13:31:45.661059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f9f410b064'
down_revision: Union[str, Sequence[str], None] = '1a1a588e7161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_runs', 'worker_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('job_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('job_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('job_runs', 'worker_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
