"""update-job-status

Revision ID: a7ff07350402
Revises: 6d2e958d03b4
Create Date: 2026-01-16 10:53:18.784850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ff07350402'
down_revision: Union[str, Sequence[str], None] = '6d2e958d03b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE job_status_enum ADD VALUE IF NOT EXISTS 'SCHEDULED'")
    op.execute("ALTER TYPE job_status_enum ADD VALUE IF NOT EXISTS 'CREATED'")
    op.execute("ALTER TYPE job_status_enum ADD VALUE IF NOT EXISTS 'ENQUEUED'")
    op.execute("ALTER TYPE job_status_enum ADD VALUE IF NOT EXISTS 'SUCCESS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
