from enum import Enum

class JobStatus(Enum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    CREATED = "CREATED"
    ENQUEUED = "ENQUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"